feat: updates homelab script

diff --git a/scripts-magic-spells/,backup-homelab b/scripts-magic-spells/,backup-homelab
--- a/scripts-magic-spells/,backup-homelab
+++ b/scripts-magic-spells/,backup-homelab
@@ -28,6 +28,11 @@ ntfy="$HOME/services/ntfy"
 # uptime kuma
 uptime_kuma="$HOME/services/uptime_kuma"
 
+# essentials
+restic="$HOME/services/restic"
+scripts="$HOME/services/scripts"
+vault="$HOME/vault"
+
 dirs=(
     "$traefik"
     "$authentik"
@@ -36,10 +41,23 @@ dirs=(
     "$ntfy"
     "$uptime_kuma"
     "$immich"
+    "$restic"
+    "$scripts"
+    "$vault"
 )
 
 mkdir -p "$HOME/backups"
 backups="$HOME/backups"
+
+assert_rsync() {
+    local dir=$1
+    shift
+    "$@" || {
+        err=$("$@" 2>&1)
+        echo "Error on rsync [$dir]: $err"
+        return 1
+    }
+}
 
 dry_run() {
     for dir in "${dirs[@]}"; do
@@ -122,24 +140,47 @@ local_backup() {
             # traefik - backup everything
             # src: ~/services/traefik/
             # dest: ~/backups/traefik/
-            sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/
+            sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ || {
+                err=$(sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ 2>&1)
+                echo "Error on rsync [$dir]: $err"
+                return 1
+            }
+            # TODO: refactor this, assert_rsync "$dir" sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/
         fi
         if [[ $dir == "$portainer" ]]; then
             # portainer - backup everything
-            sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ # dest: ~/backups/portainer
+            # dest: ~/backups/portainer
+            sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ || {
+                err=$(sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ 2>&1)
+                echo "Error on rsync [$dir]: $err"
+                return 1
+            }
             sudo chown -R "$(whoami)":"$(whoami)" "$bk_dir"/data
         fi
         if [[ $dir == "$uptime_kuma" ]]; then
             # uptime_kuma - backup everything
-            sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ # dest: ~/backups/uptime_kuma
+            # dest: ~/backups/uptime_kuma
+            sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ || {
+                err=$(sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ 2>&1)
+                echo "Error on rsync [$dir]: $err"
+                return 1
+            }
         fi
         if [[ $dir == "$authentik" ]]; then
             # authentik - backup everything
             # dest: ~/backups/authentik
-            sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/
+            sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ || {
+                err=$(sudo rsync -azvh --delete --progress "$dir"/ "$bk_dir"/ 2>&1)
+                echo "Error on rsync [$dir]: $err"
+                return 1
+            }
             # dest: ~/backups/authentik/postgres-backup.sql
             timestamp=$(date +%s%3N)
-            docker exec -i authentik-postgres /usr/local/bin/pg_dump --username authentik-pg-admin authentik-pg-db >"$bk_dir"/postgres-backup-"$timestamp".sql
+            docker exec -i authentik-postgres /usr/local/bin/pg_dump --username authentik-pg-admin authentik-pg-db >"$bk_dir"/postgres-backup-"$timestamp".sql || {
+                err=$(docker exec -i authentik-postgres /usr/local/bin/pg_dump --username authentik-pg-admin authentik-pg-db 2>&1)
+                echo "Error on docker pg_dump [$dir]: $err"
+                return 1
+            }
         fi
         if [[ $dir == "$ntfy" ]]; then
             # ntfy - backup everything
@@ -158,7 +199,7 @@ local_backup() {
             echo "Latest dump file: $latest_zip"
             docker cp "$(docker ps -qf 'name=^gitea$')":/tmp/"$latest_zip" "$bk_dir/dumps/" || {
                 echo "Error: Failed to copy $latest_zip from container."
-                exit 1
+                return 1
             }
             echo "Gitea dump completed."
         fi
