feat: NEW ADDED USB MOUNT AND UNMOUNT working perfectly now

diff --git a/scripts-magic-spells/,usb-mount b/scripts-magic-spells/,usb-mount
--- a/scripts-magic-spells/,usb-mount
+++ b/scripts-magic-spells/,usb-mount
@@ -2,14 +2,17 @@
 
 # NOTE: use `lsblk` to identify the correct usbpart (if different then change usbpart value)
 
-mountpoint="/run/media/$(whoami)/ejsmain"
+set -e
+
+mountpoint="/mnt/$(whoami)/ejsmain"
+# mountpoint="/run/media/$(whoami)/ejsmain" # alternative mountpoint (can see in thunar)
 usbpart="/dev/sdb1"
 
 # ensure that the mountpoint exists
 if [ ! -d "$mountpoint" ]; then
 	# create mountpoint
 	echo "[ INFO ] No ejsmain detected.... creating mountpoint at $mountpoint"
-	sudo mkdir "$mountpoint"
+	sudo mkdir -p "$mountpoint"
 fi
 
 # open with cryptsetup
@@ -19,6 +22,9 @@ sudo cryptsetup open "$usbpart" ejsmain || {
 }
 
 # mount
-sudo mount /dev/mapper/ejsmain "$mountpoint"
+sudo mount /dev/mapper/ejsmain "$mountpoint" || {
+	echo "[ ERROR ] Unable to mount device."
+	exit 1
+}
 
 echo "[ SUCCESS ] Device mounted at $mountpoint"
diff --git a/scripts-magic-spells/,usb-unmount b/scripts-magic-spells/,usb-unmount
--- a/scripts-magic-spells/,usb-unmount
+++ b/scripts-magic-spells/,usb-unmount
@@ -1,8 +1,12 @@
 #!/bin/sh
 
+# NOTE: This script is for unmounting and encrypting/locking the USB device.
+# --> i know there are two error handling logic `set -e` and `|| {...; exit 1}`, im just paranoid kek
+
 set -e
 
-mountpoint="/run/media/$(whoami)/ejsmain"
+mountpoint="/mnt/$(whoami)/ejsmain"
+# mountpoint="/run/media/$(whoami)/ejsmain" # alternative mountpoint (can see in thunar)
 usbdisk="/dev/sdb"
 
 # ensure that the mountpoint exists
@@ -17,16 +21,15 @@ if [ -d "$mountpoint" ]; then
 	notify-send "Device unmounted." "$mountpoint has been unmounted."
 
 	# close with cryptsetup (encrypt)
-	if ! sudo cryptsetup close ejsmain; then
+	sudo cryptsetup close ejsmain || {
 		echo "[ ERROR ] Unable to close the device."
 		exit 1
-	fi
+	}
 
-	sudo eject "$usbdisk"
-	# this is simplified by `set -e`:
-	# if [ $? -ne 0 ]; then
-	# 	echo "[ ERROR ] Unable to eject the device."
-	# fi
+	sudo eject "$usbdisk" || {
+		echo "[ ERROR ] Unable to eject the device."
+		exit 1
+	}
 
 	echo "[ SUCCESS ] 🔒 Device is now ENCRYPTED and LOCKED. "
 	notify-send " 🔒 Device is now ENCRYPTED and LOCKED." "You can now safely remove your USB Device."
